/**
 * The generated `main.ts` map in README.md must match the markers in the file.
 *
 * `tools/gen-map.mjs` derives the map's line ranges from the `//#region` markers in
 * `src/app/main.ts`. Deriving them is what stops ordinary edits from falsifying the
 * table — but only if the table is actually regenerated, so this fails the build when
 * it is stale, with the command to fix it.
 *
 * This is the same `--check` the CLI exposes, run in-process so it costs nothing.
 *
 * It also enforces the two properties the generator cannot get right on its own,
 * because they are about the markers rather than the arithmetic:
 *   - a region's anchors must actually occur inside it (otherwise the marker is
 *     pointing at code that has since moved elsewhere);
 *   - every region needs a name and a description, since a row with neither is a line
 *     in a table that tells a reader nothing.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { readRegions, render } from '../tools/gen-map.mjs';

const root = join(import.meta.dirname, '..');
const src = readFileSync(join(root, 'src', 'app', 'main.ts'), 'utf8');
const readme = readFileSync(join(root, 'README.md'), 'utf8');
const BEGIN = '<!-- MAP:main.ts BEGIN — generated by tools/gen-map.mjs, do not edit by hand -->';
const END = '<!-- MAP:main.ts END -->';

const regions = readRegions(src);
const lines = src.split('\n');

describe('the generated main.ts map', () => {
  it('main.ts still declares its regions', () => {
    expect(regions.length).toBeGreaterThan(10);
  });

  it('is up to date with the markers (run `npm run map:update` if this fails)', () => {
    const a = readme.indexOf(BEGIN);
    const b = readme.indexOf(END);
    expect(a, 'README.md is missing the MAP BEGIN sentinel').toBeGreaterThan(-1);
    expect(b, 'README.md is missing the MAP END sentinel').toBeGreaterThan(-1);
    const current = readme.slice(a, b + END.length);
    expect(current, 'the README map is stale — run `npm run map:update`').toBe(
      render(regions, lines.length),
    );
  });

  it('every anchor occurs inside the region that names it', () => {
    const problems: string[] = [];
    for (const r of regions)
      for (const anchor of r.anchors) {
        // Anchors are written for a human (`loop()`, `await FontData.load`); match the
        // leading identifier, which is the part you would actually grep for.
        const name = anchor.replace(/\(.*/, '').replace(/[^\w$].*$/, '');
        if (name.length < 3) continue;
        const re = new RegExp(`\\b${name.replace(/\$/g, '\\$')}\\b`);
        if (!lines.slice(r.start - 1, r.end).some((l) => re.test(l)))
          problems.push(`\`${name}\` is not in ${r.start}–${r.end} ("${r.name}")`);
      }
    expect(
      problems,
      `a //#region marker names an anchor that is not in its region:\n  ${problems.join('\n  ')}\n` +
        '  The code moved, or the anchor was renamed — update the marker in main.ts.',
    ).toEqual([]);
  });

  it('every region has a name and a description', () => {
    const thin = regions.filter((r) => !r.name || !r.desc).map((r) => `line ${r.start}: "${r.name}"`);
    expect(thin, `region markers missing a name or description:\n  ${thin.join('\n  ')}`).toEqual([]);
  });
});
