#!/usr/bin/env node
/**
 * Regenerate the README's map of `src/app/main.ts` from markers in the file itself.
 *
 *     npm run map:update      # rewrite the table
 *     npm run map:update -- --check   # fail if it is stale (what the test does)
 *
 * ── Why the numbers are derived and not written ──────────────────────────────
 * The map used to be a hand-maintained table of absolute line ranges. Because the
 * ranges had to tile the file exactly, ANY edit that changed main.ts's line count
 * falsified it — so the most-edited file in the repo also carried a documentation
 * chore on every change, and the test enforcing it fired on mechanical churn rather
 * than on a region actually moving. That is a tax, and a tax people learn to resent.
 *
 * Now the source of truth is a marker at the head of each region:
 *
 *     //#region Room load & audio wiring | anchors: loadRoom, loadSoundPkg | ...prose | Hot
 *
 * A region runs from its marker to the line before the next one (the last runs to EOF),
 * so the ranges are a consequence of where the markers sit. Move code and the numbers
 * follow by themselves; a region only needs human attention when its BOUNDARY moves,
 * which is exactly when a human should be thinking about it.
 *
 * Marker grammar, pipe-separated, first field required:
 *     //#region <Region name> [| anchors: a, b, c] [| <description>] [| Hot]
 * Anchors are grep targets — the names worth searching for to land in the region.
 * `Hot` marks a region recent history keeps returning to.
 *
 * ── The README table is GENERATED ────────────────────────────────────────────
 * Everything between the MAP sentinels in README.md is output. Do not hand-edit it;
 * edit the marker in main.ts and re-run. `--check` is wired into the test suite so a
 * stale table fails `npm test` rather than rotting silently.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const SRC = join(root, 'src', 'app', 'main.ts');
const README = join(root, 'README.md');
const BEGIN = '<!-- MAP:main.ts BEGIN — generated by tools/gen-map.mjs, do not edit by hand -->';
const END = '<!-- MAP:main.ts END -->';

/** Parse the region markers out of main.ts and turn them into ranges. */
export function readRegions(text = readFileSync(SRC, 'utf8')) {
  const lines = text.split('\n');
  const marks = [];
  lines.forEach((l, i) => {
    const m = l.match(/^\/\/#region\s+(.*)$/);
    if (m) marks.push({ line: i + 1, spec: m[1].trim() });
  });
  return marks.map((mk, i) => {
    const parts = mk.spec.split('|').map((s) => s.trim());
    const name = parts.shift() ?? '';
    let anchors = '';
    let hot = false;
    const prose = [];
    for (const p of parts) {
      if (/^anchors:/i.test(p)) anchors = p.replace(/^anchors:\s*/i, '');
      else if (/^hot$/i.test(p)) hot = true;
      else if (p) prose.push(p);
    }
    return {
      name,
      anchors: anchors ? anchors.split(',').map((a) => a.trim()).filter(Boolean) : [],
      desc: prose.join(' — '),
      hot,
      start: mk.line,
      // A region ends where the next one begins; the last runs to the end of the file.
      end: i + 1 < marks.length ? marks[i + 1].line - 1 : lines.length,
    };
  });
}

function table(regions) {
  const head = [
    '| Lines | Region | Anchors — grep these | What lives here |',
    '| --- | --- | --- | --- |',
  ];
  const rows = regions.map((r) => {
    const anchors = r.anchors.length ? r.anchors.map((a) => `\`${a}\``).join(', ') : '—';
    const desc = r.desc + (r.hot ? ' **Hot.**' : '');
    return `| ${r.start}–${r.end} | ${r.name} | ${anchors} | ${desc} |`;
  });
  return [...head, ...rows].join('\n');
}

export function render(regions, lineCount) {
  return [
    BEGIN,
    '',
    `*${regions.length} regions over ${lineCount} lines. Generated from the \`//#region\` markers in`,
    '`src/app/main.ts` — edit a marker there, then run `npm run map:update`.*',
    '',
    table(regions),
    '',
    END,
  ].join('\n');
}

const text = readFileSync(SRC, 'utf8');
const regions = readRegions(text);
if (!regions.length) {
  console.error('[gen-map] no //#region markers found in src/app/main.ts');
  process.exit(1);
}
const block = render(regions, text.split('\n').length);
const readme = readFileSync(README, 'utf8');
const a = readme.indexOf(BEGIN);
const b = readme.indexOf(END);
if (a === -1 || b === -1) {
  console.error(`[gen-map] README.md is missing the MAP sentinels:\n  ${BEGIN}\n  ${END}`);
  process.exit(1);
}
const updated = readme.slice(0, a) + block + readme.slice(b + END.length);

if (process.argv.includes('--check')) {
  if (updated !== readme) {
    console.error('[gen-map] the README map is out of date — run `npm run map:update`');
    process.exit(1);
  }
  console.log(`[gen-map] up to date (${regions.length} regions)`);
} else {
  writeFileSync(README, updated);
  console.log(`[gen-map] wrote ${regions.length} regions to README.md`);
}
